ALTER TABLE `licenses`
  MODIFY COLUMN `expires_at` DATETIME NULL DEFAULT NULL,
  MODIFY COLUMN `activated_at` DATETIME NULL DEFAULT NULL,
  MODIFY COLUMN `last_verified_at` DATETIME NULL DEFAULT NULL;
